apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout
data:
  RETAIL_CHECKOUT_PERSISTENCE_PROVIDER: redis
  RETAIL_CHECKOUT_PERSISTENCE_REDIS_URL: "" # Change this to your ElastiCache Redis endpoint with port, e.g. my-redis-cluster.xxxxxx.use1.cache.amazonaws.com:6379
  RETAIL_CHECKOUT_ENDPOINTS_ORDERS: http://orders:80